### ISSUE TITLE
Roll Up Board - Nothing on Backlog list

### ISSUE THREAD

**Issue by AnnBF** [ALM-Rangers/Roll-Up-Board-Widget-Extension#39]
I have installed and tried to add the roll-up widget to my dash board.  It added but when I try to edit it the backlog box is empty.  
[Rollup issue.docx](https://github.com/ALM-Rangers/Roll-Up-Board-Widget-Extension/files/1753356/Rollup.issue.docx)

**Comment by jdshkolnik** [comment]
I'm having same problem in my account. It seems to be timing out.

![image](https://user-images.githubusercontent.com/2047520/37423784-1744bc96-2795-11e8-851f-434774563a34.png)

**Comment by wpschaub** [comment]
@jdshkolnik are you still experiencing this issue? We just pushed a hotfix which should have fixed the issue for you.

**Comment by jdshkolnik** [comment]
@wpschaub Still happening.

**Comment by wpschaub** [comment]
Are you seeing any warnings or errors on the Browser F12 Debugger console?

**Comment by enkol** [comment]
For me it's working in Firefox, but broken in IE11.

IE11 error is `Object doesn't support property or method 'includes'` in `configuration.js (1,2008)`
This could be fixed with a polyfill (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)) or by directly using `indexOf`instead of `includes`.

**Comment by jeffrey-opdam** [comment]
Related to #24

**Comment by jeffrey-opdam** [comment]
We have discussed internally. We currently do not support IE.
